# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
    body_listener:
        default_format: json
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    param_fetcher_listener:  force
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }